Spring2025SWD392-NET1709-DiAnLauThai/BE-Project

src/main/java/com/be/back_end/model/Designs.java, src/main/java/com/be/back_end/model/Feedback.java, src/main/java/com/be/back_end/model/Materials.java, src/main/java/com/be/back_end/model/Order.java, src/main/java/com/be/back_end/model/Orderitems.java, src/main/java/com/be/back_end/model/Roles.java, src/main/java/com/be/back_end/model/Transactions.java, src/main/java/com/be/back_end/model/Tshirts.java, src/main/java/com/be/back_end/model/User.java
=> add packages

src/main/java/com/be/back_end/config/VNPayConfig.java, src/main/java/com/be/back_end/controller/TranscationController.java, src/main/java/com/be/back_end/dto/request/TransactionRequest.java, src/main/java/com/be/back_end/dto/response/TransactionResponse.java, src/main/java/com/be/back_end/service/TranscationService/IVNPayService.java, src/main/java/com/be/back_end/service/TranscationService/TranscationService.java, src/main/java/com/be/back_end/utils/VNPayUtils.java
=> Transcation API Done

src/main/java/com/be/back_end/controller/BookingController.java, src/main/java/com/be/back_end/controller/TranscationController.java, src/main/java/com/be/back_end/dto/response/BookingCreateResponse.java, src/main/java/com/be/back_end/repository/BookingRepository.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java, src/main/java/com/be/back_end/service/BookingService/IBookingService.java, src/main/java/com/be/back_end/service/TranscationService/IVNPayService.java, src/main/java/com/be/back_end/service/TranscationService/TranscationService.java, src/main/java/com/be/back_end/utils/VNPayUtils.java
=> add vnpay to booking

src/main/java/com/be/back_end/dto/request/BookingCreateRequest.java, src/main/java/com/be/back_end/dto/request/TaskCreateRequest.java, src/main/java/com/be/back_end/dto/response/BookingCreateResponse.java, src/main/java/com/be/back_end/enums/TshirtsEnums.java, src/main/java/com/be/back_end/model/Bookings.java, src/main/java/com/be/back_end/model/Task.java, src/main/java/com/be/back_end/repository/TasKRepository.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java, src/main/java/com/be/back_end/service/TaskService/TaskService.java
=> fix booking to task flow

src/main/java/com/be/back_end/controller/BookingController.java, src/main/java/com/be/back_end/controller/BookingDetailsController.java, src/main/java/com/be/back_end/controller/TaskController.java, src/main/java/com/be/back_end/dto/request/TshirtCreateRequest.java, src/main/java/com/be/back_end/dto/response/BookingDetailResponseDTO.java, src/main/java/com/be/back_end/dto/response/BookingResponse.java, src/main/java/com/be/back_end/repository/BookingDetailsRepository.java, src/main/java/com/be/back_end/repository/BookingRepository.java, src/main/java/com/be/back_end/service/BookingDetailService/BookingdetailService.java, src/main/java/com/be/back_end/service/BookingDetailService/IBookingdetailService.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java, src/main/java/com/be/back_end/service/BookingService/IBookingService.java
add get all booking with get all booking detail by bookingid
=> add get all booking with get all booking detail by bookingid

src/main/java/com/be/back_end/controller/TaskController.java, src/main/java/com/be/back_end/dto/response/BookingDetailResponseDTO.java, src/main/java/com/be/back_end/repository/TaskRepository.java, src/main/java/com/be/back_end/service/BookingDetailService/BookingdetailService.java, src/main/java/com/be/back_end/service/TaskService/ITaskService.java, src/main/java/com/be/back_end/service/TaskService/TaskService.java
make light fix for  booking detail and add get tasks for designer
=> make light fix for  booking detail and add get tasks for designer

src/main/java/com/be/back_end/controller/AccountController.java, src/main/java/com/be/back_end/model/Bookings.java, src/main/java/com/be/back_end/model/Feedback.java, src/main/java/com/be/back_end/model/TshirtFeedback.java, src/main/java/com/be/back_end/model/Tshirts.java, src/main/java/com/be/back_end/repository/AccountRepository.java, src/main/java/com/be/back_end/service/AccountService/AccountService.java, src/main/java/com/be/back_end/service/AccountService/IAccountService.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java, src/main/java/com/be/back_end/service/FeedbackService/FeedbackService.java
=> remake feedback logic

src/main/java/com/be/back_end/BackEndApplication.java, src/main/java/com/be/back_end/controller/TranscationController.java, src/main/java/com/be/back_end/dto/response/BookingResponse.java, src/main/java/com/be/back_end/dto/response/PaginatedResponseDTO.java, src/main/java/com/be/back_end/repository/TaskRepository.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java, src/main/java/com/be/back_end/service/EmailService/EmailService.java, src/main/java/com/be/back_end/service/TaskService/TaskService.java
optimize assign task add return url from fe for callback api
=> optimize assign task add return url from fe for callback api

src/main/java/com/be/back_end/model/Bookings.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java
add missing types of date for booking
=> add missing types of date for booking

src/main/java/com/be/back_end/dto/response/BookingResponse.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java
=> lightly fix booking response

src/main/java/com/be/back_end/controller/ColorController.java, src/main/java/com/be/back_end/dto/request/ColorDTO.java, src/main/java/com/be/back_end/service/ColorService/ColorService.java, src/main/java/com/be/back_end/service/ColorService/IColorService.java
=> fix color response dto

src/main/java/com/be/back_end/model/Bookingdetails.java, src/main/java/com/be/back_end/model/ModificationForm.java, src/main/java/com/be/back_end/model/RefundForm.java, src/main/java/com/be/back_end/repository/ModificationRequestRepository.java, src/main/java/com/be/back_end/repository/RefundRequestRepository.java, src/main/java/com/be/back_end/service/ModificationRequestService/IModificationRequestService.java, src/main/java/com/be/back_end/service/ModificationRequestService/ModificationRequestService.java, src/main/java/com/be/back_end/service/RefundRequestService/IRefundRequestService.java, src/main/java/com/be/back_end/service/RefundRequestService/RefundRequestService.java
FIX confusing naming of table's name
=> FIX confusing naming of table's name

src/main/java/com/be/back_end/controller/TshirtsController.java, src/main/java/com/be/back_end/enums/TransactionStatusEnum.java, src/main/java/com/be/back_end/service/CloudinaryService/CloudinaryService.java, src/main/java/com/be/back_end/service/CloudinaryService/ICloudinaryService.java, src/main/java/com/be/back_end/service/TranscationService/TranscationService.java
=> fix booking api

src/main/java/com/be/back_end/controller/TshirtsController.java, src/main/java/com/be/back_end/dto/request/RefundCreateRequest.java, src/main/java/com/be/back_end/service/CloudinaryService/CloudinaryService.java, src/main/java/com/be/back_end/service/CloudinaryService/ICloudinaryService.java, src/main/java/com/be/back_end/service/ColorService/ColorService.java, src/main/java/com/be/back_end/service/TranscationService/ITranscationService.java, src/main/java/com/be/back_end/service/TranscationService/TranscationService.java
=> fix get color

src/main/java/com/be/back_end/enums/TransactionStatusEnum.java, src/main/java/com/be/back_end/enums/TransactionTypeEnum.java, src/main/java/com/be/back_end/model/Bookings.java, src/main/java/com/be/back_end/model/Transaction.java, src/main/java/com/be/back_end/repository/BookingRepository.java, src/main/java/com/be/back_end/repository/TranscationRepository.java, src/main/java/com/be/back_end/service/TranscationService/TranscationService.java
modify transaction and booking table fields
=> modify transaction and booking table fields

src/main/java/com/be/back_end/controller/BookingController.java, src/main/java/com/be/back_end/controller/TranscationController.java, src/main/java/com/be/back_end/controller/TshirtsController.java, src/main/java/com/be/back_end/dto/request/CancelBookingRequest.java, src/main/java/com/be/back_end/dto/response/BookingResponse.java, src/main/java/com/be/back_end/dto/response/BookingResponseNoLinkDTO.java, src/main/java/com/be/back_end/enums/BookingEnums.java, src/main/java/com/be/back_end/enums/TshirtsEnums.java, src/main/java/com/be/back_end/model/Bookings.java, src/main/java/com/be/back_end/service/BookingDetailService/BookingdetailService.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java, src/main/java/com/be/back_end/service/BookingService/IBookingService.java, src/main/java/com/be/back_end/service/CloudinaryService/CloudinaryService.java, src/main/java/com/be/back_end/service/CloudinaryService/ICloudinaryService.java, src/main/java/com/be/back_end/service/TaskService/TaskService.java, src/main/java/com/be/back_end/service/TranscationService/IVNPayService.java, src/main/java/com/be/back_end/service/TranscationService/TranscationService.java, src/main/java/com/be/back_end/utils/VNPayUtils.java
complete api to cancel booking, complete api for paying remain
=> complete api to cancel booking, complete api for paying remain

src/main/java/com/be/back_end/model/Bookingdetails.java, src/main/java/com/be/back_end/model/Designs.java, src/main/java/com/be/back_end/model/Tshirts.java, src/main/java/com/be/back_end/repository/BookingDetailsRepository.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java, src/main/java/com/be/back_end/service/BookingService/IBookingService.java, src/main/java/com/be/back_end/service/TaskService/TaskService.java, src/main/java/com/be/back_end/service/TshirtsService/TshirtsService.java
fix tables relationship of tshirt design booking details , add update  date for when assign tshirt
=> fix tables relationship of tshirt design booking details , add update  date for when assign tshirt

src/main/java/com/be/back_end/dto/response/BookingResponseNoLinkDTO.java, src/main/java/com/be/back_end/service/BookingDetailService/BookingdetailService.java
add designer name for booking detail response
=> add designer name for booking detail response

src/main/java/com/be/back_end/config/WebSecurityConfig.java, src/main/java/com/be/back_end/controller/AccountController.java, src/main/java/com/be/back_end/controller/TaskController.java, src/main/java/com/be/back_end/service/TaskService/TaskService.java
fix confirm task bug, add authorization for /accounts api
=> fix confirm task bug, add authorization for /accounts api

src/main/java/com/be/back_end/config/WebSecurityConfig.java, src/main/java/com/be/back_end/controller/AccountController.java, src/main/java/com/be/back_end/dto/response/BookingResponseNoLinkDTO.java, src/main/java/com/be/back_end/service/BookingDetailService/BookingdetailService.java, src/main/java/com/be/back_end/service/TaskService/TaskService.java
add more response fields for booking details, fix select tshirt
=> add more response fields for booking details, fix select tshirt

src/main/java/com/be/back_end/config/WebSecurityConfig.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java, src/main/java/com/be/back_end/service/EmailService/EmailService.java, src/main/java/com/be/back_end/service/EmailService/IEmailService.java, src/main/java/com/be/back_end/service/TaskService/TaskService.java
fix data type not compatible with async
=> fix data type not compatible with async

src/main/java/com/be/back_end/repository/TshirtsRepository.java, src/main/java/com/be/back_end/service/TshirtsService/TshirtsService.java
fix get all tshirts to only get tshirts that arent in any booking detail
=> fix get all tshirts to only get tshirts that arent in any booking detail

src/main/java/com/be/back_end/controller/BookingDetailsController.java, src/main/java/com/be/back_end/dto/response/BookingResponseInDetail.java, src/main/java/com/be/back_end/dto/response/BookingResponseInDetailCus.java, src/main/java/com/be/back_end/service/BookingDetailService/BookingdetailService.java, src/main/java/com/be/back_end/service/BookingDetailService/IBookingdetailService.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java, src/main/java/com/be/back_end/service/TaskService/TaskService.java
add new get booking detail for customer, fix cancel not updating booking status
=> add new get booking detail for customer, fix cancel not updating booking status

src/main/java/com/be/back_end/controller/ColorController.java, src/main/java/com/be/back_end/controller/TshirtsController.java, src/main/java/com/be/back_end/dto/request/ColorCreateRequest.java, src/main/java/com/be/back_end/dto/response/TshirtsDTO.java, src/main/java/com/be/back_end/model/Account.java, src/main/java/com/be/back_end/model/Tshirts.java, src/main/java/com/be/back_end/repository/TshirtsRepository.java, src/main/java/com/be/back_end/service/BookingDetailService/BookingdetailService.java, src/main/java/com/be/back_end/service/BookingService/BookingService.java, src/main/java/com/be/back_end/service/ColorService/ColorService.java, src/main/java/com/be/back_end/service/ColorService/IColorService.java, src/main/java/com/be/back_end/service/TshirtsService/TshirtsService.java
fix database logic, fix color create, fix tshirts getAll
=> fix database logic, fix color create, fix tshirts getAll

src/main/java/com/be/back_end/controller/AuthController.java, src/main/java/com/be/back_end/controller/TshirtsController.java, src/main/java/com/be/back_end/dto/request/RefreshTokenRequest.java, src/main/java/com/be/back_end/dto/response/TshirtsListAvailableResponse.java, src/main/java/com/be/back_end/dto/response/TshirtsListDesignerResponse.java, src/main/java/com/be/back_end/enums/FeedbackTypeEnums.java, src/main/java/com/be/back_end/model/Feedback.java, src/main/java/com/be/back_end/model/Tshirts.java, src/main/java/com/be/back_end/repository/TshirtsRepository.java, src/main/java/com/be/back_end/service/AccountService/AccountService.java, src/main/java/com/be/back_end/service/AccountService/IAccountService.java, src/main/java/com/be/back_end/service/FeedbackService/FeedbackService.java, src/main/java/com/be/back_end/service/TshirtsService/ITshirtsService.java, src/main/java/com/be/back_end/service/TshirtsService/TshirtsService.java
fix feedback type datatype and add get 2 type of get all for tshirts
=> fix feedback type datatype and add get 2 type of get all for tshirts

src/main/java/com/be/back_end/service/TaskService/TaskService.java, src/main/java/com/be/back_end/service/TranscationService/TransactionService.java
minor fix for transaction amount when create transaction
=> minor fix for transaction amount when create transaction

src/main/java/com/be/back_end/model/Tshirts.java, src/main/java/com/be/back_end/service/AccountService/AccountDetailsImpl.java, src/main/java/com/be/back_end/service/TshirtsService/TshirtsService.java
remove field in tshirt add login check
=> remove field in tshirt add login check

src/main/java/com/be/back_end/service/TaskService/TaskService.java
=> fix getAll task

src/main/java/com/be/back_end/controller/BookingController.java
fix into request param public(again)
=> fix into request param public(again)

src/main/java/com/be/back_end/dto/response/BookingResponseInDetail.java, src/main/java/com/be/back_end/service/BookingDetailService/BookingdetailService.java
add isPublic for get Booking detail
=> add isPublic for get Booking detail

src/main/java/com/be/back_end/controller/AuthController.java, src/main/java/com/be/back_end/controller/FeedbackController.java, src/main/java/com/be/back_end/service/FeedbackService/FeedbackService.java, src/main/java/com/be/back_end/service/FeedbackService/IFeedbackService.java
=> fix get tshirt feedback

src/main/java/com/be/back_end/controller/TshirtsController.java, src/main/java/com/be/back_end/dto/request/TshirtsUpdateRequest.java, src/main/java/com/be/back_end/service/TshirtsService/ITshirtsService.java, src/main/java/com/be/back_end/service/TshirtsService/TshirtsService.java
=> fix update tshirt controller
